/**
 * Thin wrapper over DeepBook's official Predict SDK
 * (`@mysten/deepbook-v3/predict`, npm).
 *
 * The SDK reads Predict state on-chain over gRPC with no server in between —
 * the supported path per the DeepBook team, and the durable one now that Sui
 * has retired JSON-RPC on its own fullnodes. Since the September 2026 mainnet
 * launch it is also the address book: its deployment record carries both
 * networks (package ids, singletons, feeds, and the quote coin — Circle USDC
 * on mainnet, a mintable test coin on testnet), selected by SUI_NETWORK.
 *
 * We use it for the things it knows better than we do:
 *
 *   - the market board (every listed market with its admission grid)
 *   - the resolved pricer (forward + rolled SVI exactly as the chain prices)
 *   - BOARD prices and exact dry-run quotes — what a trade would actually
 *     pay, fees included — as opposed to our own model's fair value
 *   - mint / deposit / account transactions, and receipt decoding
 *
 * Our strategy, risk and ledger layers stay ours; this is a data source and
 * a tx builder. The SDK never signs.
 */

import {
  PredictClient,
  cost as sdkCost,
  probabilityToRaw,
  type PredictConfig,
} from '@mysten/deepbook-v3/predict';
import type { Transaction } from '@mysten/sui/transactions';
import { makeSuiClient, suiNetwork } from '../exec/sui-client.js';
import { log } from '../util/log.js';

export interface SdkMarket {
  id: string;
  expiryMs: number;
  /** Strike granularity in USD. */
  tickSize: number;
  /** Coarser USD step every new finite mint strike must sit on. */
  admissionTickSize: number;
  mintPaused: boolean;
  referencePrice: number | null;
}

export interface BoardPrice {
  up: number;
  down: number;
}

let client: PredictClient | undefined;

function predict(): PredictClient {
  if (!client) {
    client = new PredictClient({
      network: suiNetwork(),
      // The SDK accepts any Sui core client; ours is the shared gRPC one.
      client: makeSuiClient() as never,
    });
  }
  return client;
}

/**
 * The SDK's deployment record for the active network: package ids, singleton
 * object ids, per-underlying feed ids and the quote coin type. Regenerated by
 * Mysten with each SDK release, so nothing downstream hardcodes an id.
 */
export function sdkConfig(): PredictConfig {
  return predict().cfg;
}

/** The deployment's settlement coin (`…::usdc::USDC` on both networks — only
 *  the package differs, so always read it, never assume it). */
export function quoteCoinType(): string {
  return process.env.PREDICT_QUOTE_COIN_TYPE || sdkConfig().quoteCoinType;
}

const num = (v: unknown): number => {
  if (typeof v === 'number') return v;
  if (typeof v === 'string') return Number(v);
  if (typeof v === 'bigint') return Number(v);
  return NaN;
};

/** The exact fill of an executed mint, decoded from the tx's Move events. */
export interface MintFill {
  /** Entry probability actually paid, 0..1 per $1 payout. */
  entryProbability: number;
  /** Max payout actually minted (chain-floored to the position lot). */
  quantityDusdc: number;
  /** Premium into LP backing. */
  netPremiumUsdc: number;
  fees: {
    trading: number;
    subsidy: number;
    builder: number;
    penalty: number;
    inventoryImpact: number;
  };
  /** All-in account debit: premium + (trading − subsidy) + builder + penalty
   *  + inventoryImpact — exactly what the chain withdrew from the wrapper. */
  costUsdc: number;
  /** Persist to redeem/claim the position later. */
  orderId: string;
}

/**
 * Decode the mint receipt from an executed transaction's events. This is the
 * fix for the ledger-vs-chain booking gap: the ledger used to record the
 * MODELED cost (quantity × our probability), so fees and fill-vs-model drift
 * accumulated as unexplained wallet movement. Returns null when the events
 * are missing or carry no mint (caller falls back to the model and says so).
 */
export function decodeMintFill(
  events:
    | Array<{ eventType?: string; type?: string; bcs?: Uint8Array | string }>
    | undefined,
): MintFill | null {
  if (!events?.length) return null;
  try {
    const r = predict().decode.mint({ events });
    const costUsdc =
      r.premium +
      (r.fees.trading - r.fees.subsidy) +
      r.fees.builder +
      r.fees.penalty +
      r.fees.inventoryImpact;
    return {
      entryProbability: r.entryProbability,
      quantityDusdc: r.quantity,
      netPremiumUsdc: r.premium,
      fees: {
        trading: r.fees.trading,
        subsidy: r.fees.subsidy,
        builder: r.fees.builder,
        penalty: r.fees.penalty,
        inventoryImpact: r.fees.inventoryImpact,
      },
      costUsdc,
      orderId: String(r.orderId),
    };
  } catch (e) {
    log.warn('svx.sdk.mint_decode_failed', {
      err: e instanceof Error ? e.message : String(e),
    });
    return null;
  }
}

/** Every market the pool lists as live-and-not-yet-settled. */
export async function listSdkMarkets(): Promise<SdkMarket[]> {
  const raw = await predict().read.markets();
  return raw
    .map((m) => ({
      id: String(m.id ?? ''),
      expiryMs: num(m.expiryMs),
      tickSize: num(m.tickSize),
      admissionTickSize: num(m.admissionTickSize),
      mintPaused: m.mintPaused === true,
      referencePrice: m.referencePrice == null ? null : num(m.referencePrice),
    }))
    .filter((m) => m.id && Number.isFinite(m.expiryMs));
}

/**
 * Board price for a strike — the protocol's own quote for both sides.
 * `strike: 'reference'` asks for the market's reference strike.
 */
export async function boardPrice(
  underlying: string,
  expiryMs: number,
  strike: number | 'reference',
): Promise<BoardPrice | null> {
  try {
    const p = await predict().read.price({ underlying, expiryMs, strike });
    const up = num(p?.up);
    const down = num(p?.down);
    if (!Number.isFinite(up) || !Number.isFinite(down)) return null;
    return { up, down };
  } catch (e) {
    log.warn('svx.sdk.board_price_failed', {
      expiryMs,
      strike: String(strike),
      err: e instanceof Error ? e.message : String(e),
    });
    return null;
  }
}

/** The chain's resolved pricer for one market: the forward it settles
 *  against and the ALREADY-ROLLED SVI surface, plus source timestamps. */
export interface ResolvedPricer {
  forward: number;
  svi: { a: number; b: number; rho: number; m: number; sigma: number };
  /** Oldest Block Scholes source time behind the snapshot (ms). */
  sourceTimestampMs: number;
}

/**
 * One simulate of the chain's `load_live_pricer`. Throws (via the SDK's
 * typed PredictMoveError) when the chain itself cannot quote — stale
 * oracle, expired market — so a successful read IS a freshness check.
 */
export async function resolvedPricer(
  underlying: string,
  expiryMs: number,
): Promise<ResolvedPricer> {
  const p = await predict().read.pricer({ underlying, expiryMs });
  const s = p.asOf;
  return {
    forward: p.forward,
    svi: { a: p.svi.a, b: p.svi.b, rho: p.svi.rho, m: p.svi.m, sigma: p.svi.sigma },
    sourceTimestampMs: Math.min(
      s.blockScholesSpotMs,
      s.blockScholesForwardMs,
      s.blockScholesSviMs,
    ),
  };
}

// ── fees ────────────────────────────────────────────────────────────────────

/** A market's snapshotted fee policy (from its `strike_exposure.config`). */
export type FeePolicy = Parameters<typeof sdkCost.mintCost>[0]['fees'];

/**
 * Parse the fee policy out of an ExpiryMarket object's json. Each market
 * snapshots its policy at creation, so this — not `SHIPPED_FEE_POLICY` — is
 * what a mint on it is charged. Null when a field is missing (caller falls
 * back to a chain quote).
 */
export function feePolicyFromMarketJson(json: Record<string, unknown>): FeePolicy | null {
  const se = json.strike_exposure as Record<string, unknown> | undefined;
  const c = se?.config as Record<string, unknown> | undefined;
  if (!c) return null;
  const big = (v: unknown): bigint | null => {
    if (v == null) return null;
    try {
      return BigInt(String(v));
    } catch {
      return null;
    }
  };
  const fields = {
    baseFee: big(c.base_fee),
    minFee: big(c.min_fee),
    expiryFeeWindowMs: big(c.expiry_fee_window_ms),
    expiryFeeMaxMultiplier: big(c.expiry_fee_max_multiplier),
    minEntryProbability: big(c.min_entry_probability),
    maxEntryProbability: big(c.max_entry_probability),
    inventoryImpactMaxRate: big(c.inventory_impact_max_rate),
    inventoryImpactScale: big(se?.inventory_impact_scale),
    backingBufferLambda: big(c.backing_buffer_lambda),
  };
  if (Object.values(fields).some((v) => v === null)) return null;
  return fields as FeePolicy;
}

/**
 * All-in cost of a binary mint — premium plus the protocol's trading fee
 * with its expiry ramp — computed locally with the SDK's exact integer port
 * of the deployed fee math. Used to book PAPER trades at what they would
 * really have cost; live trades book the decoded receipt instead.
 *
 * Returns null when the fee math refuses the order (below min premium,
 * outside the entry band) — the same order would abort on-chain.
 */
export function estimateMintCost(args: {
  fees: FeePolicy;
  expiryMs: number;
  nowMs: number;
  /** Probability of the side being bought, 0..1 (the entry price). */
  sideProbability: number;
  direction: 'up' | 'down';
  quantity: number;
}): { cost: number; costPerContract: number; fee: number } | null {
  try {
    const up = args.direction === 'up' ? args.sideProbability : 1 - args.sideProbability;
    // probabilityToRaw is exact and rejects >9 decimals, which float
    // complements (1 − 0.772 = 0.22799999999999998) routinely produce.
    const upRaw = probabilityToRaw(Number(up.toFixed(9)));
    const r = sdkCost.mintCost({
      fees: args.fees,
      expiryMs: args.expiryMs,
      nowMs: args.nowMs,
      quantity: args.quantity,
      // An UP order is (strike, +inf]; a DOWN order is (−inf, strike].
      probabilities:
        args.direction === 'up'
          ? { lowerUp: upRaw, higherUp: null }
          : { lowerUp: null, higherUp: upRaw },
    } as never) as { cost: number; costPerContract: number };
    return {
      cost: r.cost,
      costPerContract: r.costPerContract,
      fee: r.cost - args.sideProbability * args.quantity,
    };
  } catch {
    return null;
  }
}

// ── account + trading (owner-scoped; the SDK builds, we sign) ────────────────

/** The owner's canonical Predict account wrapper id — derived, no chain read. */
export function wrapperIdFor(owner: string): string {
  return predict().wrapperIdFor(owner);
}

/** Account custody balance in quote units (USDC on mainnet). */
export async function accountBalance(owner: string): Promise<number | null> {
  try {
    return await predict().read.balance(owner);
  } catch {
    return null; // no account yet, or unreadable
  }
}

/** Does the owner's derived account wrapper exist on-chain yet? */
export async function accountExists(owner: string): Promise<boolean> {
  try {
    const res = await makeSuiClient().getObject({ objectId: wrapperIdFor(owner) });
    return !!res.object;
  } catch {
    return false;
  }
}

/** Fund the account from the owner's quote coin; `create` also creates and
 *  shares the wrapper in the same PTB (first deposit only). */
export function buildDepositTx(owner: string, amount: number, create: boolean): Transaction {
  return predict().tx.deposit(owner, amount, create ? { create: true } : undefined);
}

/** Withdraw from the account to the owner's address balance. */
export function buildWithdrawTx(owner: string, amount: number): Transaction {
  return predict().tx.withdraw(owner, amount);
}

export interface BinaryOrder {
  underlying: string;
  expiryMs: number;
  /** Pin the exact ExpiryMarket object we priced (no re-resolution). */
  marketId: string;
  /** Admission-grid USD strike, or the market's own reference strike (the
   *  one finite strike the chain admits off the admission grid). */
  strike: number | 'reference';
  direction: 'up' | 'down';
  /** Max payout, USD. */
  quantity: number;
}

/**
 * Exact dry-run of the mint against the real account and market — real fees,
 * real code path. Throws the same typed error the real mint would, so it
 * doubles as preflight.
 */
export async function quoteMint(
  owner: string,
  o: BinaryOrder,
): Promise<{ cost: number; entryProbability: number; quantity: number }> {
  const q = await predict().read.quoteMint(
    owner,
    {
      underlying: o.underlying,
      expiryMs: o.expiryMs,
      marketId: o.marketId,
      strike: o.strike,
      side: o.direction,
    },
    { quantity: o.quantity },
  );
  return { cost: q.cost, entryProbability: q.entryProbability, quantity: q.quantity };
}

/** Mint with BOTH slippage caps set — the SDK's defaults are uncapped. */
export async function buildMintTx(
  owner: string,
  o: BinaryOrder,
  caps: { maxCost: number; maxProbability: number },
): Promise<Transaction> {
  return predict().tx.mint(
    owner,
    {
      underlying: o.underlying,
      expiryMs: o.expiryMs,
      marketId: o.marketId,
      strike: o.strike,
      side: o.direction,
    },
    {
      quantity: o.quantity,
      // Raw amounts are 1e6 integers — round the ceiling UP to 6 dp.
      maxCost: Math.ceil(caps.maxCost * 1e6) / 1e6,
      maxProbability: Math.min(0.99, caps.maxProbability),
    },
  );
}
